### ISSUE TITLE
No effect for a user

### ISSUE THREAD

**Issue by ryanlovett** [berkeley-dsep-infra/interact#2]
When clewis13 attempted to click on @SamLau95's bit.ly link for the lab today, the user was presented a view of the notebook but no files were pulled. The interact log had no record of her visiting the service. I manually copied the files into her account on the hub.

This was in the middle of lab and I didn't want to interfere with her completing the task. I suspect it is a device-specific issue like caching behavior or some such thing, but I couldn't debug at the time.

She was running Chrome on a PC.

**Comment by ryanlovett** [comment]
Actually, a second user dreamhunter was having the same problem. Chrome on a PC.

She did not initially have a bmail account so I walked her through creating it. She then was able to login to ds8, but Garrett reports: "Logging out/in and restarting the server appear ineffective." I'll look into it.

**Comment by papajohn** [comment]
I heard 3 more reports from TAs of students that couldn't load the lab files. They said it took them 20-40 minutes of clicking on the link until the lab finally loaded for them. Fahad thought it was only affecting students for whom he had just created an account.

**Comment by SamLau95** [comment]
Hmm. I ran two labs without any issues.

One caveat with pulling in the lab is that if the student isn't logged in, the files won't be pulled in.

I find that the procedure of asking students to log into data8.berkeley.edu first, start their server, **then** hit the interact link to load the lab works very consistently.

**Comment by papajohn** [comment]
I suspect this behavior will be fixed by #8.
